version: "3.8"

services:
  mysql:
    image: mariadb:11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: nest-events
    ports:
      - 3306:3306

#  postgres:
#    image: postgres:13.1
#    environment:
#      POSTGRES_PASSWORD: example
#    ports:
#      - 5432:5432
